Limpieza del conjunto de datos construido a partir de informacion pública de la **Encuesta Nacional de Salud y Nutrición (ENSANUT) 2024**, publicada por el Instituto Nacional de Salud Pública (INSP) de México.\
url: https://ensanut.insp.mx/encuestas/ensanutcontinua2024/descargas.php

In [9]:
import numpy as np
import pandas as pd

In [14]:
db = pd.read_csv('Diabetes_Mexico.csv')

In [17]:
db.head()

,folio_i,folio_int,sexo,edad,Ciudad,Peso,Estatura,imc,muestra_suero,ac_urico,...,creat,glu_suero,insulina,trig,hb1ac,ponde_venosa,estrato,est_sel,ponde_hemo,riesgo_diabetes_cat
0,2024_01001010,2024_01001010_01,Mujer,89.0,AGUASCALIENTES,NaN,NaN,NaN,1.0,"4,1",...,"0,62",166.0,"4,7",107.0,NaN,"2245,917738",3.0,13.0,"2888,530238",2
1,2024_01001012,2024_01001012_01,Mujer,71.0,AGUASCALIENTES,NaN,NaN,32.0,1.0,"4,3",...,"0,64",98.0,"9,6",132.0,NaN,"2245,917738",3.0,13.0,"2888,530238",1
2,2024_01001016,2024_01001016_02,Mujer,57.0,AGUASCALIENTES,"80,25","170,6",NaN,1.0,"4,9",...,"0,6",128.0,"4,7",263.0,6.0,"4047,445276",3.0,13.0,NaN,2
3,2024_01001016,2024_01001016_05,Mujer,20.0,AGUASCALIENTES,"68,6","166,2",NaN,1.0,"4,9",...,"0,63",112.0,"10,1",238.0,NaN,"13079,14232",3.0,13.0,"13776,80526",2
4,2024_01001031,2024_01001031_01,Hombre,74.0,AGUASCALIENTES,NaN,NaN,NaN,1.0,"6,4",...,"1,09",97.0,"10,2",135.0,NaN,"5292,158204",3.0,13.0,"5824,779445",0

In [15]:
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2549 entries, 0 to 2548
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   folio_i              2549 non-null   object
 1   folio_int            2549 non-null   object
 2   sexo                 2549 non-null   object
 3   edad                 2524 non-null   float64
 4   Ciudad               2549 non-null   object
 5   Peso                 1829 non-null   object
 6   Estatura             1829 non-null   object
 7   imc                  35 non-null     float64
 8   muestra_suero        2549 non-null   float64
 9   ac_urico             2549 non-null   object
 10  albu                 2549 non-null   object
 11  col_hdl              2549 non-null   object
 12  col_ldl              2549 non-null   float64
 13  colest               2549 non-null   float64
 14  creat                2549 non-null   object
 15  glu_suero            2549 non-null   float64
 16  insulina             2549 non-null   object
 17  trig                 2549 non-null   float64
 18  hb1ac                241 non-null    float64
 19  ponde_venosa         2450 non-null   object
 20  estrato              2549 non-null   float64
 21  est_sel              2549 non-null   float64
 22  ponde_hemo           1569 non-null   object
 23  riesgo_diabetes_cat  2549 non-null   int64
dtypes: float64(10), int64(1), object(13)
memory usage: 478.1+ KB

In [16]:
db.describe()

,edad,imc,muestra_suero,col_ldl,colest,glu_suero,trig,hb1ac,estrato,est_sel,riesgo_diabetes_cat
count,2524.000000,35.000000,2549.0,2549.000000,2549.000000,2549.000000,2549.000000,241.000000,2549.000000,2549.000000,2549.000000
mean,35.763074,29.971429,1.0,91.143978,143.023146,105.541389,153.564143,5.809129,2.088662,167.799137,0.663790
std,319.672846,7.633077,0.0,29.904939,42.458243,51.922275,126.311311,1.450890,0.825411,94.420560,0.939469
min,-7975.000000,15.000000,1.0,16.000000,25.000000,32.000000,24.000000,5.000000,1.000000,11.000000,0.000000
25%,34.000000,25.000000,1.0,71.000000,115.000000,83.000000,87.000000,5.000000,1.000000,83.000000,0.000000
50%,47.500000,30.000000,1.0,88.000000,139.000000,92.000000,123.000000,5.000000,2.000000,172.000000,0.000000
75%,62.000000,32.500000,1.0,108.000000,166.000000,104.000000,181.000000,6.000000,3.000000,242.000000,2.000000
max,95.000000,56.000000,1.0,354.000000,625.000000,1116.000000,2834.000000,12.000000,3.000000,323.000000,2.000000

In [57]:
col_con_comas = db[['Peso','Estatura','ac_urico','creat','insulina','albu','ponde_venosa','ponde_hemo','col_hdl','col_ldl','colest','glu_suero','trig','hb1ac','estrato','']]

In [58]:
# Cambiamos las columnas con comas por puntos decimales
for col in col_con_comas:
    if db[col].dtype == 'O': #Si es de tipo Object (texto)
        db[col] = db[col].str.replace(',','.').astype(float)

In [59]:
# Eliminamos los valores nulos en las columnas 'sexo', 'Peso' y 'Estatura'
for col in db[['edad','Peso','Estatura']]:
    db[col] = db.groupby('sexo')[col].transform(lambda x:x.fillna(x.mean()))

In [60]:
# Calculamos la columna imc
db['imc'] = db['Peso']/(db['Estatura']/100)**2
db

,folio_i,folio_int,sexo,edad,Ciudad,Peso,Estatura,imc,muestra_suero,ac_urico,...,creat,glu_suero,insulina,trig,hb1ac,ponde_venosa,estrato,est_sel,ponde_hemo,riesgo_diabetes_cat
0,2024_01001010,2024_01001010_01,Mujer,89.0,AGUASCALIENTES,72.645492,154.666608,30.367955,1.0,4.1,...,0.62,166.0,4.7,107.0,NaN,2245.917738,3.0,13.0,2888.530238,2
1,2024_01001012,2024_01001012_01,Mujer,71.0,AGUASCALIENTES,72.645492,154.666608,30.367955,1.0,4.3,...,0.64,98.0,9.6,132.0,NaN,2245.917738,3.0,13.0,2888.530238,1
2,2024_01001016,2024_01001016_02,Mujer,57.0,AGUASCALIENTES,80.250000,170.600000,27.573188,1.0,4.9,...,0.60,128.0,4.7,263.0,6.0,4047.445276,3.0,13.0,NaN,2
3,2024_01001016,2024_01001016_05,Mujer,20.0,AGUASCALIENTES,68.600000,166.200000,24.834881,1.0,4.9,...,0.63,112.0,10.1,238.0,NaN,13079.142320,3.0,13.0,13776.805260,2
4,2024_01001031,2024_01001031_01,Hombre,74.0,AGUASCALIENTES,83.099629,167.951429,29.459928,1.0,6.4,...,1.09,97.0,10.2,135.0,NaN,5292.158204,3.0,13.0,5824.779445,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544,2024_32056012,2024_32056012_01,Mujer,66.0,ZACATECAS,72.645492,154.666608,30.367955,1.0,4.8,...,0.72,89.0,6.4,179.0,NaN,6532.590705,3.0,323.0,9897.955004,0
2545,2024_32056022,2024_32056022_02,Mujer,51.0,ZACATECAS,97.600000,171.200000,33.299852,1.0,5.8,...,0.69,98.0,35.2,126.0,NaN,13055.895570,3.0,323.0,NaN,0
2546,2024_32056024,2024_32056024_01,Hombre,45.0,ZACATECAS,90.950000,172.400000,30.600476,1.0,6.7,...,0.82,94.0,17.8,119.0,NaN,6394.811934,3.0,323.0,NaN,0
2547,2024_32056024,2024_32056024_02,Mujer,38.0,ZACATECAS,69.300000,152.800000,29.681547,1.0,4.6,...,0.56,88.0,10.7,132.0,5.0,13189.495730,3.0,323.0,20012.012060,0
2548,2024_32056029,2024_32056029_01,Hombre,44.0,ZACATECAS,76.850000,164.400000,28.434150,1.0,6.5,...,0.67,136.0,3.7,73.0,NaN,63723.960800,3.0,323.0,NaN,2

In [61]:
# Clasificamos el imc por categorías
def clasif(imc):
    if imc<18.5:
        return 'Bajo Peso'
    elif imc<24.9:
        return 'Normal'
    elif imc<29.9:
        return 'Sobrepeso'
    else:
        return 'Obesidad'

In [62]:
db['imc'] = db['imc'].apply(clasif)

In [63]:
db

,folio_i,folio_int,sexo,edad,Ciudad,Peso,Estatura,imc,muestra_suero,ac_urico,...,creat,glu_suero,insulina,trig,hb1ac,ponde_venosa,estrato,est_sel,ponde_hemo,riesgo_diabetes_cat
0,2024_01001010,2024_01001010_01,Mujer,89.0,AGUASCALIENTES,72.645492,154.666608,Obesidad,1.0,4.1,...,0.62,166.0,4.7,107.0,NaN,2245.917738,3.0,13.0,2888.530238,2
1,2024_01001012,2024_01001012_01,Mujer,71.0,AGUASCALIENTES,72.645492,154.666608,Obesidad,1.0,4.3,...,0.64,98.0,9.6,132.0,NaN,2245.917738,3.0,13.0,2888.530238,1
2,2024_01001016,2024_01001016_02,Mujer,57.0,AGUASCALIENTES,80.250000,170.600000,Sobrepeso,1.0,4.9,...,0.60,128.0,4.7,263.0,6.0,4047.445276,3.0,13.0,NaN,2
3,2024_01001016,2024_01001016_05,Mujer,20.0,AGUASCALIENTES,68.600000,166.200000,Normal,1.0,4.9,...,0.63,112.0,10.1,238.0,NaN,13079.142320,3.0,13.0,13776.805260,2
4,2024_01001031,2024_01001031_01,Hombre,74.0,AGUASCALIENTES,83.099629,167.951429,Sobrepeso,1.0,6.4,...,1.09,97.0,10.2,135.0,NaN,5292.158204,3.0,13.0,5824.779445,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544,2024_32056012,2024_32056012_01,Mujer,66.0,ZACATECAS,72.645492,154.666608,Obesidad,1.0,4.8,...,0.72,89.0,6.4,179.0,NaN,6532.590705,3.0,323.0,9897.955004,0
2545,2024_32056022,2024_32056022_02,Mujer,51.0,ZACATECAS,97.600000,171.200000,Obesidad,1.0,5.8,...,0.69,98.0,35.2,126.0,NaN,13055.895570,3.0,323.0,NaN,0
2546,2024_32056024,2024_32056024_01,Hombre,45.0,ZACATECAS,90.950000,172.400000,Obesidad,1.0,6.7,...,0.82,94.0,17.8,119.0,NaN,6394.811934,3.0,323.0,NaN,0
2547,2024_32056024,2024_32056024_02,Mujer,38.0,ZACATECAS,69.300000,152.800000,Sobrepeso,1.0,4.6,...,0.56,88.0,10.7,132.0,5.0,13189.495730,3.0,323.0,20012.012060,0
2548,2024_32056029,2024_32056029_01,Hombre,44.0,ZACATECAS,76.850000,164.400000,Sobrepeso,1.0,6.5,...,0.67,136.0,3.7,73.0,NaN,63723.960800,3.0,323.0,NaN,2

In [65]:
# Exportamos los datos ya limpios
db.to_excel('Diabetes_Mexico_Limpio.xlsx',index=False)